# Use the official Python image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the app.py file into the container
COPY . .

# Run the Python script
CMD ["python", "app.py"]
